### ISSUE TITLE
Compatibility with which Version?

### ISSUE THREAD

**Issue by 13abylon** [santo74/vertx-arangodb#1]
Hello,

Since we have no email address from you, I will write you an issue :)

First of all, thanks for the work all the work! 

We switched from Arangodb.org to Arangodb.com. So if there are any links in your driver they should be changed.

Also we will hopefully release 2.3 this week so you can check if your driver is compatible :)

If you want to you can email me: thomas (at) arangodb.com

Thanks for your help!

Regards
Thomas

**Comment by santo74** [comment]
Hi Thomas,

Thanks for letting me know.
The integration tests as well as the build file for drone.io do have pointers to arangodb.org, so I'll update them right away.

And of course I'll verify the compatibility with ArangoDB 2.3 as soon as it is released ;-)

sANTo
